name: msbuild
on:
  push:
    branches:
      - master # or the name of your main branch

jobs:
  CICD:
    name: CICD
    runs-on: windows-latest
    steps:
      
     #Add msbuild to PATH
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
        with:
         vswhere-path: "file:///C:/Program%20Files%20(x86)/Microsoft%20Visual%20Studio/2019/BuildTools/MSBuild/Current/Bin/"
  
     #To build dotnet application using MSBuild
      - name: Build
        run: msbuild ./RenderHTMLinView.sln
      
