name: TESTCICD
on:
  push:
    branches:
      # - main                                            # name of your main branch
        - testcicd                                        # name of the feature brach
jobs:
  TESTCICD:
    name: TESTCICD
    runs-on: windows-latest
    
    steps:
    
     #Add msbuild to PATH                                 # Integrate msbuild to GHA
      - name:  Setup MSBuild.exe
        uses: microsoft/Setup-MSBuild@v1
  
     #To build dotnet application using MSBuild           # Add the Solution file to msbuild
      - name: MSBuild
        working-directory: src
        run: msbuild RenderHTMLinView.sln 
