name: TESTCICD
on:
  push:
    branches:
        - main                                            # name of your main branch
        - testcicd                                        # name of the feature brach
jobs:
  TESTCICD:
    name: TESTCICD
    runs-on: windows-latest
    
    steps:
    
     #Add msbuild to PATH                                 # Integrate msbuild to GHA
      - name:  Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
  
     #To build dotnet application using MSBuild           # Add the Solution file to msbuild
      - name: MSBuild
        run:  msbuild.exe ./RenderHTMLinView.sln
        
   
